export const siteMetadata = {
  title: 'Passave',
  author: 'Fahmin Guliyev',
  headerTitle: 'passave',
  description: 'Secure Password Manager',
  language: 'en-us',
  theme: 'dark',
  siteUrl: 'https://passave.fahminguliyev.com',
  siteRepo: 'https://github.com/faxmishok/passave-nextjs',
  siteLogo: '/ps-logo.svg',
  siteLogoFooter: '/ps-logo-footer.svg',
  email: 'fahminguliyev6@gmail.com',
  github: 'https://github.com/faxmishok',
  twitter: 'https://x.com/notchwonders',
  facebook: 'https://facebook.com/faxmishok',
  instagram: 'https://instagram.com/notchstrident',
  linkedin: 'https://www.linkedin.com/in/fahmin/',
  locale: 'en-US',
};
